version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rs_telecom
      POSTGRES_USER: rs_user
      POSTGRES_PASSWORD: rs_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
